// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpobxrwcugvqrmohzrej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwb2J4cndjdWd2cXJtb2h6cmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDY4MzIsImV4cCI6MjA2OTEyMjgzMn0.PRvZKKNV3AWhryFOerQFmyf0n6pi0L1PJLgG6db2QSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});